// Artifact Select
export const REQUEST_ARTIFACT_SELECT_START = 'REQUEST_ARTIFACT_SELECT_START';
export const REQUEST_ARTIFACT_SELECT_SUCCESS = 'REQUEST_ARTIFACT_SELECT_SUCCESS';
export const REQUEST_ARTIFACT_SELECT_FAILED = 'REQUEST_ARTIFACT_SELECT_FAILED';
// Slice History
export const REQUEST_SLICE_HISTORY_START = 'REQUEST_SLICE_HISTORY_START';
export const REQUEST_SLICE_HISTORY_SUCCESS = 'REQUEST_SLICE_HISTORY_SUCCESS';
export const REQUEST_SLICE_HISTORY_FAILED = 'REQUEST_SLICE_HISTORY_FAILED';
// Send Slice
export const SEND_SLICE_START = 'SEND_SLICE_START';
export const SEND_SLICE_SUCCESS = 'SEND_SLICE_SUCCESS';
export const SEND_SLICE_FAILED = 'SEND_SLICE_FAILED';

